
//binary search (ikkilik qidiruv)
function binary_search(array,item){

//1. BERILGAN ARRAY NING ENG KICHIK(LOW) AND ENG KATTA INDEXLARINI ANQILAB OLAMIZ

//ENG KATTA INDEX ARRAY UZUNLIGIDAN BITTA KICHKINA INDEX BOLADI , CHUNKI ARRAYDA ITEM LAR INDEXI NOLDAN BOSHLANADI
let high=array.length-1;
//ENG KICHIK INDEX NOL
let low=0


//2. WHILE LOOP ENG KICHIK INDEX ENG KATTA INDEX DAN KICHIK YKI TENG BOLGUNICHA ITERATSIYA BOLADI
while (low<=high) {
    // 3 . ARRAY NING ORTA INDEXINI ANIQLAYMIZ
    //4.ARRAYNING ORTA INDEXI ENG KATTA AND ENG KICHIK INDEXLAR QOSHILMASINI 2 GA BOLINGANIGA TENG BOLADI
    let mid = Math.floor((high + low) / 2);

    if (item==array[mid]){
        //5.AGAR ORTA INDEX DAGI ITEM VA BIZ ARGUMENT SIFATIDA KIRITGAN ITEM TENG BOLSA , USHA URTA INDEX NI QAYTARAMIZ
        return mid
    }
    //6.AGAR ORTA INDEX DAGI ITEM ARGUMENT SIFATIDA KIRITILGAN ITEMDAN KATTA BOLSA MASALAN , 100 TA ITEM LI ARRAY VA BIZ AGRUMENT SIFATIDA
    //12 NI KIRITDIK VA ORTA INDEX 51 DAN KICHIK, USHBU HOLATDA , ARRAY NING ENG KATTA INDEXI 50 GA QAYTADI , AGAR TESKARI HOLAT BOLSA ARRAYNING ENG KICHIK QIYMATI 51 GA
    //7.YANI ORTA INDEX DAN BITTA KOPGA OZGARADI, MISOL UCHUN 85 AGUMENT BERILDI , ORTA INDEX 51 DAN KATTA VA ENG KICHIK INDEX ENDI 51 GA (ORTA INDEXDAN BITTA KOPGA) OZGARDI
    if (array[mid]>item) {
        high=array[mid]-1
    }else{
        low=array[mid]+1
    }
}

//8.AGAR UMUMAN WHILE LOOP ISHLAMASA YANI ITEM TOPILMASA NULL QAYTARADI
return null
}

console.log(binary_search([1,2,3,4,5,6,7,8,9,10],3));
console.log(binary_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 20));